# These are supported funding model platforms
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [fiodortretyakov]   # GitHub Sponsors username(s)
# patreon:            # Patreon username
# open_collective:    # Open Collective slug
# ko_fi:              # Ko-fi username
# buy_me_a_coffee:    # Buy Me a Coffee username
# custom: ['https://example.com/donate']   # up to 4 custom URLs
